[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pex"
author = "The PEX developers"
author-email = "pantsbuild@gmail.com"
home-page = "https://github.com/pantsbuild/pex"
description-file = "README.rst"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: Unix",
  "Operating System :: POSIX :: Linux",
  "Operating System :: MacOS :: MacOS X",
  "Programming Language :: Python",
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
requires-python = ">=2.7,<=3.9,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"

[tool.flit.metadata.requires-extra]
# For improved subprocess robustness under python2.7.
subprocess = ["subprocess32>=3.2.7; python_version<'3'"]

[tool.flit.scripts]
pex = "pex.bin.pex:main"

[tool.flit.entrypoints."distutils.commands"]
# Make bdist_pex available for folks who install the pex distribution.
bdist_pex = "pex.commands.bdist_pex:bdist_pex"

[tool.flit.sdist]
include = ["CHANGES.rst"]

[tool.black]
line-length = 100
target-version = ["py27"]
exclude = '''
/(
  | \.git
  | \pex/vendor/_vendored
  | \.pyenv_test
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100
default_section = "THIRDPARTY"
known_first_party = "pex"
